<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data=[

             [   'id'                =>  '1',
                'parent_id'         =>  null,
                'category_name'     =>  'Web, Mobile, and Software Development',
                'category_short_name'   =>  'Web_Mobile_and_Software_Development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '2',
                'parent_id'         =>  '1',
                'category_name'     =>  'Web development',
                'category_short_name'   =>  'Web_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '3',
                'parent_id'         =>  '1',
                'category_name'     =>  'Mobile app development',
                'category_short_name'   =>  'Mobile_app_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '4',
                'parent_id'         =>  '1',
                'category_name'     =>  'Desktop software development',
                'category_short_name'   =>  'Desktop_software_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '5',
                'parent_id'         =>  '1',
                'category_name'     =>  'Game development',
                'category_short_name'   =>  'Game_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
            [   'id'                =>  '6',
                'parent_id'         =>  '1',
                'category_name'     =>  'E-commerce development',
                'category_short_name'   =>  'E_commerce_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
              [   'id'                =>  '7',
                'parent_id'         =>  null,
                'category_name'     =>  'IT and Network Services',
                'category_short_name'   =>  'IT_and_Network_Services',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
               [   'id'                =>  '8',
                'parent_id'         =>  '7',
                'category_name'     =>  'IT support',
                'category_short_name'   =>  'IT_support',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   [   'id'                =>  '9',
                'parent_id'         =>  '7',
                'category_name'     =>  'Network management',
                'category_short_name'   =>  'Network_management',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '10',
                'parent_id'         =>  '7',
                'category_name'     =>  'Cybersecurity',
                'category_short_name'   =>  'Cybersecurity',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
             [   'id'                =>  '11',
                'parent_id'         =>  null,
                'category_name'     =>  'Data Science and Analytics',
                'category_short_name'   =>  'Data_Science_and_Analytics',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
             [   'id'                =>  '12',
                'parent_id'         =>  '11',
                'category_name'     =>  'Data analysis',
                'category_short_name'   =>  'Data_analysis',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
             [   'id'                =>  '13',
                'parent_id'         =>  '11',
                'category_name'     =>  'Data visualization',
                'category_short_name'   =>  'Data_visualization',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
               [   'id'                =>  '14',
                'parent_id'         =>  '11',
                'category_name'     =>  'Machine learning',
                'category_short_name'   =>  'Machine_learning',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '15',
                'parent_id'         =>  null,
                'category_name'     =>  'Design and Creativity',
                'category_short_name'   =>  'Design_and_Creativity',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
             [   'id'                =>  '16',
                'parent_id'         =>  '15',
                'category_name'     =>  'Graphic design',
                'category_short_name'   =>  'Graphic_design',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '17',
                'parent_id'         =>  '15',
                'category_name'     =>  'Logo and branding design',
                'category_short_name'   =>  'Logo_and_branding_design',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '18',
                'parent_id'         =>  '15',
                'category_name'     =>  'Web and mobile design',
                'category_short_name'   =>  'Web_and_mobile_design',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],    [   'id'                =>  '19',
                'parent_id'         =>  '15',
                'category_name'     =>  'Illustration',
                'category_short_name'   =>  'Illustration',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],     [   'id'                =>  '20',
                'parent_id'         =>  '15',
                'category_name'     =>  'Animation',
                'category_short_name'   =>  'Animation',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
               [   'id'                =>  '21',
                'parent_id'         =>  '15',
                'category_name'     =>  'UI/UX design',
                'category_short_name'   =>  'UI_UX_design',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
             [   'id'                =>  '22',
                'parent_id'         =>  '15',
                'category_name'     =>  '3D modeling and visualization',
                'category_short_name'   =>  '3D_modeling_and_visualization',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], [   'id'                =>  '23',
                'parent_id'         =>  '15',
                'category_name'     =>  'Photography and editing',
                'category_short_name'   =>  'Photography_and_editing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  [   'id'                =>  '24',
                'parent_id'         =>  '15',
                'category_name'     =>  'Audio and video production',
                'category_short_name'   =>  'Audio_and_video_production',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '25',
                'parent_id'         =>  '15',
                'category_name'     =>  'Creative writing',
                'category_short_name'   =>  'Creative_writing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '26',
                'parent_id'         =>  null,
                'category_name'     =>  'Writing and Translation',
                'category_short_name'   =>  'Writing_and_Translation',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
              [   'id'                =>  '27',
                'parent_id'         =>  '26',
                'category_name'     =>  'Article and blog writing',
                'category_short_name'   =>  'Article_and_blog_writing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
              [   'id'                =>  '28',
                'parent_id'         =>  '26',
                'category_name'     =>  'Technical writing',
                'category_short_name'   =>  'Technical_writing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
              [   'id'                =>  '29',
                'parent_id'         =>  '26',
                'category_name'     =>  'Creative writing',
                'category_short_name'   =>  'Creative_writing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
             [   'id'                =>  '30',
                'parent_id'         =>  '26',
                'category_name'     =>  'Translation',
                'category_short_name'   =>  'Translation',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
              [   'id'                =>  '31',
                'parent_id'         =>  null,
                'category_name'     =>  'Administrative Support and Virtual Assistance',
                'category_short_name'   =>  'Administrative_Support_and_Virtual_Assistance',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
              [   'id'                =>  '32',
                'parent_id'         =>  '31',
                'category_name'     =>  'Data entry',
                'category_short_name'   =>  'Data_entry',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
             [   'id'                =>  '33',
                'parent_id'         =>  '31',
                'category_name'     =>  'Virtual assistance',
                'category_short_name'   =>  'Virtual_assistance',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '34',
                'parent_id'         =>  '31',
                'category_name'     =>  'Customer service',
                'category_short_name'   =>  'Customer_service',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
               [   'id'                =>  '35',
                'parent_id'         =>  null,
                'category_name'     =>  'Sales and Marketing',
                'category_short_name'   =>  'Sales_and_Marketing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
               [   'id'                =>  '36',
                'parent_id'         =>  '35',
                'category_name'     =>  'Digital marketing',
                'category_short_name'   =>  'Digital_marketing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '37',
                'parent_id'         =>  '35',
                'category_name'     =>  'SEO services',
                'category_short_name'   =>  'SEO_services',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '38',
                'parent_id'         =>  '35',
                'category_name'     =>  'Social media management',
                'category_short_name'   =>  'Social_media_management',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
      

           [   'id'                =>  '39',
                'parent_id'         =>  '35',
                'category_name'     =>  'Content marketing',
                'category_short_name'   =>  'Content_marketing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '40',
                'parent_id'         =>  '35',
                'category_name'     =>  'Email marketing',
                'category_short_name'   =>  'Email_marketing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '41',
                'parent_id'         =>  '35',
                'category_name'     =>  'Advertising and PPC campaigns',
                'category_short_name'   =>  'Advertising_and_PPC_campaigns',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '42',
                'parent_id'         =>  '35',
                'category_name'     =>  'Sales strategy and business development',
                'category_short_name'   =>  'Sales_strategy_and_business_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '43',
                'parent_id'         =>  null,
                'category_name'     =>  'Artificial Intelligence/Machine Learning',
                'category_short_name'   =>  'Artificial_Intelligence_Machine_Learning',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '44',
                'parent_id'         =>  '43',
                'category_name'     =>  'AI application development',
                'category_short_name'   =>  'AI_application_development',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '45',
                'parent_id'         =>  '43',
                'category_name'     =>  'Machine learning model creation',
                'category_short_name'   =>  'Machine_learning_model_creation',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   

             [   'id'                =>  '46',
                'parent_id'         =>  '43',
                'category_name'     =>  'Natural Language Processing (NLP)',
                'category_short_name'   =>  'Natural_Language_Processing_NLP',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   

            
            [   'id'                =>  '47',
                'parent_id'         =>  '43',
                'category_name'     =>  'Audio and visual analysis',
                'category_short_name'   =>  'Audio_and_visual_analysis',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '48',
                'parent_id'         =>  '43',
                'category_name'     =>  'Recommendation systems',
                'category_short_name'   =>  'Recommendation_systems',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '49',
                'parent_id'         =>  null,
                'category_name'     =>  'Career Counseling',
                'category_short_name'   =>  'Career_Counseling',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   

            [   'id'                =>  '50',
                'parent_id'         =>  '49',
                'category_name'     =>  'CV and resume writing',
                'category_short_name'   =>  'CV_and_resume_writing',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '51',
                'parent_id'         =>  '49',
                'category_name'     =>  'Job application and interview coaching',
                'category_short_name'   =>  'Job_application_and_interview_coaching',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '52',
                'parent_id'         =>  '49',
                'category_name'     =>  'Career planning and strategies',
                'category_short_name'   =>  'Career_planning_and_strategies',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
            [   'id'                =>  '53',
                'parent_id'         =>  '49',
                'category_name'     =>  'Personal branding',
                'category_short_name'   =>  'Personal_branding',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '54',
                'parent_id'         =>  '49',
                'category_name'     =>  'Job search techniques',
                'category_short_name'   =>  'Job_search_techniques',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '55',
                'parent_id'         =>  null,
                'category_name'     =>  'Education and Teaching',
                'category_short_name'   =>  'Education_and_Teaching',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
             [   'id'                =>  '56',
                'parent_id'         =>  '55',
                'category_name'     =>  'Education consulting',
                'category_short_name'   =>  'Education_consulting',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
               [   'id'                =>  '57',
                'parent_id'         =>  '55',
                'category_name'     =>  'Private tutoring',
                'category_short_name'   =>  'Private_tutoring',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],   
        ];

         DB::table('categories')->insert($data);
    }
}
