<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data=[

                [   'id'                =>  '1',
                'country_zone'   =>  'Europe',
                'name'     =>  '',
                'parent_id'         =>  null,
                'country_code'         =>  '',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
             [   'id'                =>  '2',
                'country_zone'   =>  '',
                'name'     =>  'Germany',
                'country_code'     =>  'DE',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '3',
                'country_zone'   =>  '',
                'name'     =>  'Austria',
                'country_code'     =>  'AT',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '4',
                'country_zone'   =>  '',
                'name'     =>  'Belgium',
                'country_code'     =>  'BE',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
            [   'id'                =>  '5',
                'country_zone'   =>  '',
                'name'     =>  'United Kingdom',
                'country_code'     =>  'GB',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
             [   'id'                =>  '6',
                'country_zone'   =>  '',
                'name'     =>  'Denmark',
                'country_code'     =>  'DK',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
            [   'id'                =>  '7',
                'country_zone'   =>  '',
                'name'     =>  'Finland',
                'country_code'     =>  'FI',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
            [   'id'                =>  '8',
                'country_zone'   =>  '',
                'name'     =>  'France',
                'country_code'     =>  'FR',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '9',
                'country_zone'   =>  '',
                'name'     =>  'Netherlands',
                'country_code'     =>  'NL',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
               [   'id'                =>  '10',
                'country_zone'   =>  '',
                'name'     =>  'Ireland',
                'country_code'     =>  'IE',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '11',
                'country_zone'   =>  '',
                'name'     =>  'Spain',
                'country_code'     =>  'ES',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '12',
                'country_zone'   =>  '',
                'name'     =>  'Sweden',
                'country_code'     =>  'SE',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '13',
                'country_zone'   =>  '',
                'name'     =>  'Switzerland',
                'country_code'     =>  'CH',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
              [   'id'                =>  '14',
                'country_zone'   =>  '',
                'name'     =>  'Italy',
                'country_code'     =>  'IT',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '15',
                'country_zone'   =>  '',
                'name'     =>  'Luxembourg',
                'country_code'     =>  'LU',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '16',
                'country_zone'   =>  '',
                'name'     =>  'Norway',
                'country_code'     =>  'NO',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
            [   'id'                =>  '17',
                'country_zone'   =>  '',
                'name'     =>  'Poland',
                'country_code'     =>  'PL',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
             [   'id'                =>  '18',
                'country_zone'   =>  '',
                'name'     =>  'Portugal',
                'country_code'     =>  'PT',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 

             [   'id'                =>  '19',
                'country_zone'   =>  'Gulf',
                'name'     =>  '',
                'country_code'     =>  '',
                'parent_id'         =>  '1',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
             [   'id'                =>  '20',
                'country_zone'   =>  '',
                'name'     =>  'Bahrain',
                'country_code'     =>  'BH',
                'parent_id'         =>  '19',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
             [   'id'                =>  '21',
                'country_zone'   =>  '',
                'name'     =>  'Qatar',
                'country_code'     =>  'QA',
                'parent_id'         =>  '19',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
            [   'id'                =>  '22',
                'country_zone'   =>  '',
                'name'     =>  'Kuwait',
                'country_code'     =>  'KW',
                'parent_id'         =>  '19',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],
             [   'id'                =>  '23',
                'country_zone'   =>  '',
                'name'     =>  'Oman',
                'country_code'     =>  'OM',
                'parent_id'         =>  '19',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
              [   'id'                =>  '24',
                'country_zone'   =>  '',
                'name'     =>  'Saudi Arabia',
                'country_code'     =>  'SA',
                'parent_id'         =>  '19',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ],  
            [   'id'                =>  '25',
                'country_zone'   =>  '',
                'name'     =>  'United Arab Emirates',
                'country_code'     =>  'AE',
                'parent_id'         =>  '19',
                'status'            =>  'active',
                'created_at'        =>  date('Y-m-d H:i:s'),
                'updated_at'        =>  date('Y-m-d H:i:s'),
            ], 
        ];

         DB::table('countries')->insert($data);
        
    }
}
